# Dependabot will run on day 3 of each month at 02:40 (Europe/Berlin timezone)
version: 2
updates:

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'cron'
      timezone: 'Europe/Berlin'
      cronjob: '40 2 3 * *'
    open-pull-requests-limit: 20
    versioning-strategy: 'increase'
    ignore:
      - dependency-name: '@types/node'
        update-types:
          - 'version-update:semver-major'
